"""Train and serve the congestion prediction model."""

from __future__ import annotations

import os
import json

import numpy as np
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_squared_error, accuracy_score, r2_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

from .config import MODEL_DIR, REPORT_DIR
from .db import log_metrics
from .sample_data import build_training_frame

os.environ.setdefault("LOKY_MAX_CPU_COUNT", "1")

try:
    from xgboost import XGBRegressor

    HAS_XGBOOST = True
except Exception:  # pragma: no cover
    from sklearn.ensemble import HistGradientBoostingRegressor

    HAS_XGBOOST = False


FEATURES = [
    "event_type",
    "event_location",
    "weather_condition",
    "crowd_size",
    "event_hour",
    "event_duration_hr",
    "historical_traffic",
    "location_baseline",
    "time_pressure",
    "road_density",
]

CATEGORICAL = ["event_type", "event_location", "weather_condition"]
NUMERIC = ["crowd_size", "event_hour", "event_duration_hr", "historical_traffic", "location_baseline", "time_pressure", "road_density"]
MODEL_PATH = MODEL_DIR / "smart_city_xgb_pipeline.joblib"
METRICS_PATH = REPORT_DIR / "smart_city_model_metrics.json"


def _model():
    if HAS_XGBOOST:
        return XGBRegressor(
            n_estimators=350,
            max_depth=5,
            learning_rate=0.05,
            subsample=0.85,
            colsample_bytree=0.85,
            reg_alpha=0.2,
            reg_lambda=1.2,
            random_state=42,
            objective="reg:squarederror",
        )
    return HistGradientBoostingRegressor(max_depth=6, learning_rate=0.05, max_iter=320, random_state=42)


def _pipeline():
    pre = ColumnTransformer(
        transformers=[
            ("cat", OneHotEncoder(handle_unknown="ignore"), CATEGORICAL),
            ("num", "passthrough", NUMERIC),
        ]
    )
    return Pipeline([("pre", pre), ("model", _model())])


def build_dataset(n_rows: int = 2200, seed: int = 42) -> pd.DataFrame:
    return build_training_frame(n_rows=n_rows, seed=seed)


def train(seed: int = 42) -> dict:
    df = build_dataset(seed=seed)
    X = df[FEATURES]
    y = df["congestion_score"].astype(float)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=seed)

    pipe = _pipeline()
    pipe.fit(X_train, y_train)
    preds = np.clip(pipe.predict(X_test), 0, 100)

    rmse = float(np.sqrt(mean_squared_error(y_test, preds)))
    r2 = float(r2_score(y_test, preds))
    class_labels = pd.cut(y_test, bins=[-1, 39, 69, 100], labels=["LOW", "MEDIUM", "HIGH"])
    pred_labels = pd.cut(preds, bins=[-1, 39, 69, 100], labels=["LOW", "MEDIUM", "HIGH"])
    accuracy = float(accuracy_score(class_labels, pred_labels))

    MODEL_DIR.mkdir(parents=True, exist_ok=True)
    import joblib

    joblib.dump(pipe, MODEL_PATH)
    feature_names = []
    try:
        feature_names = list(pipe.named_steps["pre"].get_feature_names_out())
    except Exception:
        feature_names = FEATURES

    importances = []
    estimator = pipe.named_steps["model"]
    if hasattr(estimator, "feature_importances_"):
        pairs = list(zip(feature_names, estimator.feature_importances_))
        pairs.sort(key=lambda x: x[1], reverse=True)
        importances = [{"feature": f, "importance": float(v)} for f, v in pairs[:10]]

    metrics = {
        "model_name": "XGBoost" if HAS_XGBOOST else "HistGradientBoosting",
        # NOTE: `accuracy` is NOT a native classifier score. It is computed by
        # binning the regressor's continuous output into LOW/MEDIUM/HIGH and
        # comparing to the binned ground truth (see `accuracy_type`). RMSE/R2 are
        # the primary regression metrics.
        "accuracy": round(accuracy, 3),
        "accuracy_type": "binned_classification (LOW/MEDIUM/HIGH)",
        "rmse": round(rmse, 3),
        "r2": round(r2, 3),
        "train_rows": int(len(X_train)),
        "test_rows": int(len(X_test)),
        # The training frame is generated by build_training_frame(); these scores
        # reflect fit on SYNTHETIC data and are not a measure of real-world skill.
        # They must be revalidated against real labelled traffic before any
        # operational or production claim is made.
        "data_source": "synthetic (build_training_frame)",
        "validation_caveat": "Metrics are on synthetic data; revalidate on real labelled traffic before production use.",
        "feature_importance": importances,
    }
    METRICS_PATH.write_text(json.dumps(metrics, indent=2))
    log_metrics(metrics["model_name"], metrics)
    return metrics


def load_model():
    import joblib

    if MODEL_PATH.exists():
        return joblib.load(MODEL_PATH)
    return None


def predict_one(model, payload: dict) -> dict:
    frame = pd.DataFrame([payload])[FEATURES]
    score = float(np.clip(model.predict(frame)[0], 0, 100))
    if score < 40:
        risk = "LOW"
    elif score < 70:
        risk = "MEDIUM"
    else:
        risk = "HIGH"
    return {"congestion_score": round(score, 1), "risk_level": risk}
